version: '3.3'

services:
  php:
    build:
      context: .
      dockerfile: Dockerfile
    entrypoint: /bin/bash
    volumes:
      - ./:/app

#services:
#  php:
#    build:
#      context: .
#      dockerfile: Dockerfile
#    entrypoint: /bin/bash
#    volumes:
#      - ./:/app